In [7]:
import numpy as np
import pandas as pd

In [8]:
from pandas import Series,DataFrame #conviniency

Series
similar to array

In [9]:
obj=pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [10]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [11]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
obj=pd.Series([4,7,-5,3],index=["d","b","a","c"])
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [16]:
obj[["a","d"]]#key to the value,metion that there's [[]]

a   -5
d    4
dtype: int64

In [17]:
obj[obj>0]

d    4
b    7
c    3
dtype: int64

In [18]:
np.exp(obj)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [20]:
"b" in obj

True

In [21]:
obj.to_dict()

{'d': 4, 'b': 7, 'a': -5, 'c': 3}

In [22]:
obj=pd.Series(obj)

In [24]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
states = ["California", "Ohio", "Oregon", "Texas"]
obj=pd.Series(sdata,index=states)
obj

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

the fuction isnull and notnull in pandas can be used to examine the missing values

In [29]:
pd.isnull(obj)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
#alignment for index
obj+pd.Series(sdata)

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [33]:
obj.name="popu"
obj.index.name="state"
obj

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: popu, dtype: float64

DataFrame

In [36]:
data={"state":["Ohio","Ohio","Ohio","Nevada","Nevada","Nevada"],
      "year":[2000,2001,2002,2001,2002,2003],
      "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [37]:
frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [38]:
frame.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [40]:
print(pd.DataFrame(data,columns=["year","state","debt"]))

   year   state debt
0  2000    Ohio  NaN
1  2001    Ohio  NaN
2  2002    Ohio  NaN
3  2001  Nevada  NaN
4  2002  Nevada  NaN
5  2003  Nevada  NaN

In [41]:
frame["state"]#that is a Series

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [42]:
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [49]:
frame["eastern"]=frame["state"]=="Ohio"#add new columns
frame

    state  year  pop  eastern
0    Ohio  2000  1.5     True
1    Ohio  2001  1.7     True
2    Ohio  2002  3.6     True
3  Nevada  2001  2.4    False
4  Nevada  2002  2.9    False
5  Nevada  2003  3.2    False

In [50]:
del frame["eastern"]
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [51]:
frame.T

          0     1     2       3       4       5
state  Ohio  Ohio  Ohio  Nevada  Nevada  Nevada
year   2000  2001  2002    2001    2002    2003
pop     1.5   1.7   3.6     2.4     2.9     3.2

In [52]:
frame.to_numpy()

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9],
       ['Nevada', 2003, 3.2]], dtype=object)